// Dashboard fakes for static content localization
// Usage: Use t(fake.key) to get the localized string

export const dashboardFakes = {
  overview: {
    welcomeBack: "dashboard.overview.welcomeBack",
    happeningToday: "dashboard.overview.happeningToday",
    totalCustomer: "dashboard.overview.totalCustomer",
    totalRevenue: "dashboard.overview.totalRevenue",
    totalDeals: "dashboard.overview.totalDeals",
    searchProductPlaceholder: "dashboard.overview.searchProductPlaceholder",
    productName: "dashboard.overview.productName",
    description: "dashboard.overview.description",
    dateTime: "dashboard.overview.dateTime",
    category: "dashboard.overview.category",
    price: "dashboard.overview.price",
    noProductsFound: "dashboard.overview.noProductsFound",
  },
  products: {
    management: "dashboard.productsManagement",
    managementDesc: "dashboard.productsManagementDesc",
    addProduct: "dashboard.addProduct",
    searchPlaceholder: "dashboard.searchProductPlaceholder",
    empty: "dashboard.noProducts",
    emptyDesc: "dashboard.noProductsDesc",
    tableHeaders: [
      "dashboard.productName",
      "dashboard.productCategory",
      "dashboard.productPrice",
      "dashboard.productStock",
      "dashboard.productStatus",
      "dashboard.productActions",
    ],
  },
  shops: {
    management: "dashboard.shopsManagement",
    managementDesc: "dashboard.shopsManagementDesc",
    addShop: "dashboard.addShop",
    searchPlaceholder: "dashboard.searchShopPlaceholder",
    empty: "dashboard.noShops",
    emptyDesc: "dashboard.noShopsDesc",
    tableHeaders: [
      "dashboard.shopName",
      "dashboard.shopOwner",
      "dashboard.shopStatus",
      "dashboard.shopCreated",
      "dashboard.shopActions",
    ],
  },
  notifications: {
    title: "dashboard.notifications.title",
    unread: "dashboard.notifications.unread",
    markAllRead: "dashboard.notifications.markAllRead",
    searchPlaceholder: "dashboard.notifications.searchPlaceholder",
    all: "dashboard.notifications.all",
    read: "dashboard.notifications.read",
    orders: "dashboard.notifications.orders",
    sellerRequest: "dashboard.notifications.sellerRequest",
    shopApproval: "dashboard.notifications.shopApproval",
    system: "dashboard.notifications.system",
    order: "dashboard.notifications.order",
    other: "dashboard.notifications.other",
    approve: "dashboard.notifications.approve",
    reject: "dashboard.notifications.reject",
    empty: "dashboard.notifications.empty",
    details: "dashboard.notifications.details",
    userName: "dashboard.notifications.userName",
    userEmail: "dashboard.notifications.userEmail",
    shopName: "dashboard.notifications.shopName",
    requestDetails: "dashboard.notifications.requestDetails",
    actions: "dashboard.notifications.actions",
    selectToView: "dashboard.notifications.selectToView",
    logApprovingSellerRequest:
      "dashboard.notifications.logApprovingSellerRequest",
    logApprovingShopCreation:
      "dashboard.notifications.logApprovingShopCreation",
    logRejectingSellerRequest:
      "dashboard.notifications.logRejectingSellerRequest",
    logRejectingShopCreation:
      "dashboard.notifications.logRejectingShopCreation",
  },
  guide: {
    welcome: "dashboard.guide.welcome",
    description: "dashboard.guide.description",
    gettingStarted: {
      title: "dashboard.guide.gettingStarted.title",
      understandingLayout: {
        title: "dashboard.guide.gettingStarted.understandingLayout.title",
        screenshot:
          "dashboard.guide.gettingStarted.understandingLayout.screenshot",
        navigationSidebar:
          "dashboard.guide.gettingStarted.understandingLayout.navigationSidebar",
        navigationSidebarDesc:
          "dashboard.guide.gettingStarted.understandingLayout.navigationSidebarDesc",
        mainContentArea:
          "dashboard.guide.gettingStarted.understandingLayout.mainContentArea",
        mainContentAreaDesc:
          "dashboard.guide.gettingStarted.understandingLayout.mainContentAreaDesc",
        topBar: "dashboard.guide.gettingStarted.understandingLayout.topBar",
        topBarDesc:
          "dashboard.guide.gettingStarted.understandingLayout.topBarDesc",
        exploreLayout:
          "dashboard.guide.gettingStarted.understandingLayout.exploreLayout",
      },
      userProfile: {
        title: "dashboard.guide.gettingStarted.userProfile.title",
        screenshot: "dashboard.guide.gettingStarted.userProfile.screenshot",
        editProfile: "dashboard.guide.gettingStarted.userProfile.editProfile",
        editProfileDesc:
          "dashboard.guide.gettingStarted.userProfile.editProfileDesc",
        changePassword:
          "dashboard.guide.gettingStarted.userProfile.changePassword",
        changePasswordDesc:
          "dashboard.guide.gettingStarted.userProfile.changePasswordDesc",
        notifications:
          "dashboard.guide.gettingStarted.userProfile.notifications",
        notificationsDesc:
          "dashboard.guide.gettingStarted.userProfile.notificationsDesc",
      },
    },
    coreFeatures: {
      title: "dashboard.guide.coreFeatures.title",
      overview: {
        title: "dashboard.guide.coreFeatures.overview.title",
        screenshot: "dashboard.guide.coreFeatures.overview.screenshot",
        description: "dashboard.guide.coreFeatures.overview.description",
        performanceCharts:
          "dashboard.guide.coreFeatures.overview.performanceCharts",
        keyIndicators: "dashboard.guide.coreFeatures.overview.keyIndicators",
        quickActions: "dashboard.guide.coreFeatures.overview.quickActions",
      },
      managingUsers: {
        title: "dashboard.guide.coreFeatures.managingUsers.title",
        screenshot: "dashboard.guide.coreFeatures.managingUsers.screenshot",
        description: "dashboard.guide.coreFeatures.managingUsers.description",
        viewUsers: "dashboard.guide.coreFeatures.managingUsers.viewUsers",
        addNewUsers: "dashboard.guide.coreFeatures.managingUsers.addNewUsers",
        editUsers: "dashboard.guide.coreFeatures.managingUsers.editUsers",
        deactivateActivateUsers:
          "dashboard.guide.coreFeatures.managingUsers.deactivateActivateUsers",
        howToEdit: {
          title: "dashboard.guide.coreFeatures.managingUsers.howToEdit.title",
          step1: "dashboard.guide.coreFeatures.managingUsers.howToEdit.step1",
          step2: "dashboard.guide.coreFeatures.managingUsers.howToEdit.step2",
          step3: "dashboard.guide.coreFeatures.managingUsers.howToEdit.step3",
          step4: "dashboard.guide.coreFeatures.managingUsers.howToEdit.step4",
          step5: "dashboard.guide.coreFeatures.managingUsers.howToEdit.step5",
        },
      },
    },
    settings: {
      title: "dashboard.guide.settings.title",
      screenshot: "dashboard.guide.settings.screenshot",
      description: "dashboard.guide.settings.description",
      generalSettings: "dashboard.guide.settings.generalSettings",
      notificationSettings: "dashboard.guide.settings.notificationSettings",
      userManagementSettings: "dashboard.guide.settings.userManagementSettings",
      changingNotificationPreferences: {
        title: "dashboard.guide.settings.changingNotificationPreferences.title",
        step1: "dashboard.guide.settings.changingNotificationPreferences.step1",
        step2: "dashboard.guide.settings.changingNotificationPreferences.step2",
        step3: "dashboard.guide.settings.changingNotificationPreferences.step3",
        step4: "dashboard.guide.settings.changingNotificationPreferences.step4",
      },
    },
    troubleshooting: {
      title: "dashboard.guide.troubleshooting.title",
      commonIssues: {
        title: "dashboard.guide.troubleshooting.commonIssues.title",
        cantFindUser: {
          title:
            "dashboard.guide.troubleshooting.commonIssues.cantFindUser.title",
          solution:
            "dashboard.guide.troubleshooting.commonIssues.cantFindUser.solution",
        },
        changesNotSaving: {
          title:
            "dashboard.guide.troubleshooting.commonIssues.changesNotSaving.title",
          solution:
            "dashboard.guide.troubleshooting.commonIssues.changesNotSaving.solution",
        },
      },
      faq: {
        title: "dashboard.guide.troubleshooting.faq.title",
        addNewAdminUser: {
          question:
            "dashboard.guide.troubleshooting.faq.addNewAdminUser.question",
          answer: "dashboard.guide.troubleshooting.faq.addNewAdminUser.answer",
        },
        exportData: {
          question: "dashboard.guide.troubleshooting.faq.exportData.question",
          answer: "dashboard.guide.troubleshooting.faq.exportData.answer",
        },
        userRoles: {
          question: "dashboard.guide.troubleshooting.faq.userRoles.question",
          answer: "dashboard.guide.troubleshooting.faq.userRoles.answer",
        },
      },
    },
    needMoreHelp: {
      title: "dashboard.guide.needMoreHelp.title",
      description: "dashboard.guide.needMoreHelp.description",
      orVisit: "dashboard.guide.needMoreHelp.orVisit",
      supportPortal: "dashboard.guide.needMoreHelp.supportPortal",
    },
  },
  profile: {
    shopNotFound: "dashboard.profile.shopNotFound",
    unableToLoadShop: "dashboard.profile.unableToLoadShop",
    noShopFound: "dashboard.profile.noShopFound",
    createShopMessage: "dashboard.profile.createShopMessage",
    about: "dashboard.profile.about",
    aboutDescription: "dashboard.profile.aboutDescription",
  },
  categories: {
    title: "categories.title",
    addCategory: "categories.addCategory",
    addNewCategory: "categories.addNewCategory",
    categoryName: "categories.categoryName",
    description: "categories.description",
    descriptionPlaceholder: "categories.descriptionPlaceholder",
    subCategories: "categories.subCategories",
    subCategoryPlaceholder: "categories.subCategoryPlaceholder",
    addSubCategory: "categories.addSubCategory",
    deleteSuccess: "categories.deleteSuccess",
    deleteError: "categories.deleteError",
    createSuccess: "categories.createSuccess",
    createError: "categories.createError",
    searchPlaceholder: "categories.searchPlaceholder",
    filterCategory: "categories.filterCategory",
    dateCreated: "categories.dateCreated",
    subCategoriesFor: "categories.subCategoriesFor",
    noSubCategories: "categories.noSubCategories",
    noCategoriesFound: "categories.noCategoriesFound",
  },
  users: {
    title: "dashboard.users.title",
    searchPlaceholder: "dashboard.users.searchPlaceholder",
    allRoles: "dashboard.users.allRoles",
    roleCustomer: "dashboard.users.roleCustomer",
    roleSeller: "dashboard.users.roleSeller",
    roleAdmin: "dashboard.users.roleAdmin",
    allStatus: "dashboard.users.allStatus",
    statusActive: "dashboard.users.statusActive",
    statusSuspended: "dashboard.users.statusSuspended",
    loading: "dashboard.users.loading",
    noUsersFound: "dashboard.users.noUsersFound",
    fetchError: "dashboard.users.fetchError",
    tableUser: "dashboard.users.tableUser",
    tableEmail: "dashboard.users.tableEmail",
    tablePhone: "dashboard.users.tablePhone",
    tableRole: "dashboard.users.tableRole",
    tableStatus: "dashboard.users.tableStatus",
    tableCreated: "dashboard.users.tableCreated",
    tableActions: "dashboard.users.tableActions",
    actions: "dashboard.users.actions",
    viewDetails: "dashboard.users.viewDetails",
    deactivate: "dashboard.users.deactivate",
    activate: "dashboard.users.activate",
    showingPage: "dashboard.users.showingPage",
    previous: "dashboard.users.previous",
    next: "dashboard.users.next",
    detailsTitle: "dashboard.users.detailsTitle",
    phone: "dashboard.users.phone",
    role: "dashboard.users.role",
    status: "dashboard.users.status",
    created: "dashboard.users.created",
    close: "dashboard.users.close",
  },
  sellerRequest: {
    title: "dashboard.sellerRequest.title",
    loading: "dashboard.sellerRequest.loading",
    fetchError: "dashboard.sellerRequest.fetchError",
    noRequestsFound: "dashboard.sellerRequest.noRequestsFound",
    approveError: "dashboard.sellerRequest.approveError",
    rejectError: "dashboard.sellerRequest.rejectError",
    tableName: "dashboard.sellerRequest.tableName",
    tableEmail: "dashboard.sellerRequest.tableEmail",
    tablePhone: "dashboard.sellerRequest.tablePhone",
    tableBusinessName: "dashboard.sellerRequest.tableBusinessName",
    tableBusinessAddress: "dashboard.sellerRequest.tableBusinessAddress",
    tableBusinessPhone: "dashboard.sellerRequest.tableBusinessPhone",
    tableTaxId: "dashboard.sellerRequest.tableTaxId",
    tableStatus: "dashboard.sellerRequest.tableStatus",
    tableSubmitted: "dashboard.sellerRequest.tableSubmitted",
    tableActions: "dashboard.sellerRequest.tableActions",
    approve: "dashboard.sellerRequest.approve",
    reject: "dashboard.sellerRequest.reject",
    approving: "dashboard.sellerRequest.approving",
    rejecting: "dashboard.sellerRequest.rejecting",
    statusPending: "dashboard.sellerRequest.statusPending",
    statusApproved: "dashboard.sellerRequest.statusApproved",
    statusRejected: "dashboard.sellerRequest.statusRejected",
  },
  navbar: {
    profile: "navbar.profile",
    backHome: "navbar.backHome",
  },
  common: {
    addToCart: "common.addToCart",
    contactUs: "common.contactUs",
    viewShop: "common.viewShop",
  },
  shopbanner: {
    contactSupplier: "banner.shopbanner.contactSupplier",
    viewCatalog: "banner.shopbanner.viewCatalog",
    verifiedSupplier: "banner.shopbanner.verifiedSupplier",
    since: "banner.shopbanner.since",
    fastDelivery: "banner.shopbanner.fastDelivery",
    reviews: "banner.shopbanner.reviews",
    products: "banner.shopbanner.products",
    services: "banner.shopbanner.services",
    status: "banner.shopbanner.status",
    taxId: "banner.shopbanner.taxId",
    commissionRate: "banner.shopbanner.commissionRate",
    payoutMethod: "banner.shopbanner.payoutMethod",
    contactEmail: "banner.shopbanner.contactEmail",
  },
  productInfo: {
    addToCart: "productInfo.addToCart",
    removeFromWishlist: "productInfo.removeFromWishlist",
    addToWishlist: "productInfo.addToWishlist",
    shareProduct: "productInfo.shareProduct",
    description: "productInfo.description",
    details: "productInfo.details",
    noDetails: "productInfo.noDetails",
    reviews: "productInfo.reviews",
  },
  relatedProducts: {
    title: "relatedProducts.title",
    loading: "relatedProducts.loading",
    error: "relatedProducts.error",
    none: "relatedProducts.none",
  },
  defaultBanner: {
    defaultTitle: "defaultBanner.defaultTitle",
  },
  VisualizePage: {
    title: "VisualizePage.title",
    describeLabel: "VisualizePage.describeLabel",
    describePlaceholder: "VisualizePage.describePlaceholder",
    uploadLabel: "VisualizePage.uploadLabel",
    extractingText: "VisualizePage.extractingText",
    descriptionTooShort: "VisualizePage.descriptionTooShort",
    descriptionLength: "VisualizePage.descriptionLength",
    descriptionSufficient: "VisualizePage.descriptionSufficient",
    visualizeButton: "VisualizePage.visualizeButton",
    processing: "VisualizePage.processing",
    summaryTitle: "VisualizePage.summaryTitle",
    generatedImageTitle: "VisualizePage.generatedImageTitle",
    failedExtractImage: "VisualizePage.failedExtractImage",
    failedExtractPDF: "VisualizePage.failedExtractPDF",
    failedSummaryOrImage: "VisualizePage.failedSummaryOrImage",
    noSummary: "VisualizePage.noSummary",
    pleaseUpload: "VisualizePage.pleaseUpload",
  },
  VisualizeSection: {
    title: "VisualizeSection.title",
    button: "VisualizeSection.button",
  },
  RecommendationsSection: {
    title: "RecommendationsSection.title",
    loading: "RecommendationsSection.loading",
    error: "RecommendationsSection.error",
    noRecommendations: "RecommendationsSection.noRecommendations",
    seeAllProducts: "RecommendationsSection.seeAllProducts",
  },
  // Add more as needed for other dashboard sections
};
